### ISSUE TITLE
Invalid file formatting on `Localizable.strings`

### ISSUE THREAD

**Issue by schdck** [Samgisaninja/unc0ver-localizations#39]
The "template" provided by @Samgisaninja seems to have an error on line 236 (see [here](https://github.com/Samgisaninja/unc0ver-localizations/blob/e2011b8933526a2cb7bd571834f48ab19ec8f81c/en-GB.lproj/Localizable.strings#L236)):

`Creating jailbreak directory..." = "Creating jailbreak directory..." = "Unable to create jailbreak directory.`

Note that there are two `=` on the same line.

I already fixed it for ptBR on PR #37 and it seems that some other translations did it as well on their translations, but someone has to check if this error is not present in any of the other already merged translations.

**Comment by gonchumon** [comment]
Thanks, I fix in es-ES translate. :)
